name: Publish to package registries
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Set version in output
        id: set-version
        run: echo "version=${{ steps.package-version.outputs.current-version }}" >> $GITHUB_OUTPUT

      - uses: arduino/setup-protoc@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn

      - name: Compile project
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: ./generated

  typescript-build-and-publish:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: generated

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@nouw'

      - name: Install dependencies
        run: yarn

      - name: Compile typescript
        run: tsc

      - name: Configure GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "registry=https://npm.pkg.github.com/OWNER/REPO" >> .npmrc

      - name: Publish to Github Packages
        run: |
          yarn pack
          npm publish package.tgz

  kotlin-build-and-publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: generated

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and publish Kotlin package
        run: ./gradlew clean build publish
        env:
          PACKAGE_ACTOR: ${{ secrets.PACKAGE_ACTOR }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
